init:
  - call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64_x86
  - SET PROJDIR=%cd%
  - mkdir C:\P
  - mkdir C:\P\lib
  - cd C:\P\lib
  - curl -L -O "https://github.com/manthey/gv/releases/download/gv-latest/gvlib.lib"
  - curl -L -O "https://github.com/manthey/gv/releases/download/gv-latest/gvlib.h"
  - curl -L -O "https://github.com/manthey/gv/releases/download/gv-latest/mem.lib"
  - curl -L -O "https://github.com/manthey/gv/releases/download/gv-latest/mem.h"
  - cd %PROJDIR%
  - SET PATH=%PATH%;%PROJDIR%\utils

build_script:
  - nmake
  - call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64
  - nmake /f Makefile64
  - dir ov.exe ansiorb.exe ansiorb64.exe

artifacts:
  - path: ov.exe
  - path: ansiorb.exe
  - path: ansiorb64.exe

deploy:
  - provider: GitHub
    tag: 'ov-latest'
    release: 'Release ov-latest'
    auth_token:
      secure: PGsGUDU6oqIy7zCyTMwIWlzf4TbJtuIgqmWb9ZLqNlM13AAaxWfDlzDlG+0CyHFx
    artifact: ov.exe, ansiorb.exe, ansiorb64.exe
    force_update: true
    on:
      branch: master

  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: Release $(appveyor_repo_tag_name)
    auth_token:
      secure: PGsGUDU6oqIy7zCyTMwIWlzf4TbJtuIgqmWb9ZLqNlM13AAaxWfDlzDlG+0CyHFx
    artifact: ov.exe, ansiorb.exe, ansiorb64.exe
    force_update: true
    on:
      appveyor_repo_tag: true
